name: fitit
services:
  - name: app
    type: web
    root_dir: ./
    install: npm ci
    build: npm run build
    start: npm start
    port: 3000
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: $DATABASE_URL
      - key: NEXTAUTH_SECRET
        value: $NEXTAUTH_SECRET
      - key: NEXTAUTH_URL
        value: $NEXTAUTH_URL 